version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    environment:
      - REDIS_URL=${REDIS_URL}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_CSE_ID=${GOOGLE_CSE_ID}
      - PATENTSVIEW_API_KEY=${PATENTSVIEW_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=production
      - DEBUG=false
      - ALLOWED_ORIGINS=["https://novitai-word-mcp-frontend.azurewebsites.net"]
      - ALLOWED_HOSTS=["*"]
      # Internal MCP Server Configuration
      - INTERNAL_MCP_HOST=localhost
      - INTERNAL_MCP_PORT=8001
      - INTERNAL_MCP_PATH=/mcp
      - INTERNAL_MCP_URL=http://localhost:8001/mcp
      - EXPOSE_MCP_PUBLICLY=false
    ports:
      - "8000:8000"  # Backend API
      - "8001:8001"  # Internal MCP Server
    restart: unless-stopped

  frontend:
    build:
      context: "./Novitai MCP"
      dockerfile: Dockerfile
      target: production
    environment:
      - NODE_ENV=production
      - REACT_APP_API_BASE_URL=https://word-addin-backend.azurewebsites.net
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: unless-stopped
